/*
 * NexoVirt REST API
 *
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using NexoVirt.Sdk.Client;
using NexoVirt.Sdk.Model;

namespace NexoVirt.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAlertsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Acknowledge an alert
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId"></param>
        /// <returns>Envelope</returns>
        Envelope AckAlert(int alertId);

        /// <summary>
        /// Acknowledge an alert
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId"></param>
        /// <returns>ApiResponse of Envelope</returns>
        ApiResponse<Envelope> AckAlertWithHttpInfo(int alertId);
        /// <summary>
        /// Create an alert rule
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAlertRuleRequest"></param>
        /// <returns>Envelope</returns>
        Envelope CreateAlertRule(CreateAlertRuleRequest createAlertRuleRequest);

        /// <summary>
        /// Create an alert rule
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAlertRuleRequest"></param>
        /// <returns>ApiResponse of Envelope</returns>
        ApiResponse<Envelope> CreateAlertRuleWithHttpInfo(CreateAlertRuleRequest createAlertRuleRequest);
        /// <summary>
        /// Delete an alert rule
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ruleId"></param>
        /// <returns>Envelope</returns>
        Envelope DeleteAlertRule(int ruleId);

        /// <summary>
        /// Delete an alert rule
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ruleId"></param>
        /// <returns>ApiResponse of Envelope</returns>
        ApiResponse<Envelope> DeleteAlertRuleWithHttpInfo(int ruleId);
        /// <summary>
        /// List alert rules
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>Envelope</returns>
        Envelope ListAlertRules(int? page = default, int? perPage = default);

        /// <summary>
        /// List alert rules
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>ApiResponse of Envelope</returns>
        ApiResponse<Envelope> ListAlertRulesWithHttpInfo(int? page = default, int? perPage = default);
        /// <summary>
        /// List alerts
        /// </summary>
        /// <remarks>
        /// Alert instances, newest first, filterable by status and severity. Paginated.
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status"> (optional)</param>
        /// <param name="severity"> (optional)</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>Envelope</returns>
        Envelope ListAlerts(string? status = default, string? severity = default, int? page = default, int? perPage = default);

        /// <summary>
        /// List alerts
        /// </summary>
        /// <remarks>
        /// Alert instances, newest first, filterable by status and severity. Paginated.
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status"> (optional)</param>
        /// <param name="severity"> (optional)</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>ApiResponse of Envelope</returns>
        ApiResponse<Envelope> ListAlertsWithHttpInfo(string? status = default, string? severity = default, int? page = default, int? perPage = default);
        /// <summary>
        /// Resolve an alert
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId"></param>
        /// <returns>Envelope</returns>
        Envelope ResolveAlert(int alertId);

        /// <summary>
        /// Resolve an alert
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId"></param>
        /// <returns>ApiResponse of Envelope</returns>
        ApiResponse<Envelope> ResolveAlertWithHttpInfo(int alertId);
        /// <summary>
        /// Update an alert rule
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ruleId"></param>
        /// <param name="createAlertRuleRequest"></param>
        /// <returns>Envelope</returns>
        Envelope UpdateAlertRule(int ruleId, CreateAlertRuleRequest createAlertRuleRequest);

        /// <summary>
        /// Update an alert rule
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ruleId"></param>
        /// <param name="createAlertRuleRequest"></param>
        /// <returns>ApiResponse of Envelope</returns>
        ApiResponse<Envelope> UpdateAlertRuleWithHttpInfo(int ruleId, CreateAlertRuleRequest createAlertRuleRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAlertsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Acknowledge an alert
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        System.Threading.Tasks.Task<Envelope> AckAlertAsync(int alertId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Acknowledge an alert
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<Envelope>> AckAlertWithHttpInfoAsync(int alertId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Create an alert rule
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAlertRuleRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        System.Threading.Tasks.Task<Envelope> CreateAlertRuleAsync(CreateAlertRuleRequest createAlertRuleRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create an alert rule
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAlertRuleRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<Envelope>> CreateAlertRuleWithHttpInfoAsync(CreateAlertRuleRequest createAlertRuleRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Delete an alert rule
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ruleId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        System.Threading.Tasks.Task<Envelope> DeleteAlertRuleAsync(int ruleId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete an alert rule
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ruleId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<Envelope>> DeleteAlertRuleWithHttpInfoAsync(int ruleId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List alert rules
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        System.Threading.Tasks.Task<Envelope> ListAlertRulesAsync(int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List alert rules
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<Envelope>> ListAlertRulesWithHttpInfoAsync(int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List alerts
        /// </summary>
        /// <remarks>
        /// Alert instances, newest first, filterable by status and severity. Paginated.
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status"> (optional)</param>
        /// <param name="severity"> (optional)</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        System.Threading.Tasks.Task<Envelope> ListAlertsAsync(string? status = default, string? severity = default, int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List alerts
        /// </summary>
        /// <remarks>
        /// Alert instances, newest first, filterable by status and severity. Paginated.
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status"> (optional)</param>
        /// <param name="severity"> (optional)</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<Envelope>> ListAlertsWithHttpInfoAsync(string? status = default, string? severity = default, int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Resolve an alert
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        System.Threading.Tasks.Task<Envelope> ResolveAlertAsync(int alertId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Resolve an alert
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<Envelope>> ResolveAlertWithHttpInfoAsync(int alertId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Update an alert rule
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ruleId"></param>
        /// <param name="createAlertRuleRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        System.Threading.Tasks.Task<Envelope> UpdateAlertRuleAsync(int ruleId, CreateAlertRuleRequest createAlertRuleRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Update an alert rule
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ruleId"></param>
        /// <param name="createAlertRuleRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<Envelope>> UpdateAlertRuleWithHttpInfoAsync(int ruleId, CreateAlertRuleRequest createAlertRuleRequest, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAlertsApi : IAlertsApiSync, IAlertsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AlertsApi : IDisposable, IAlertsApi
    {
        private NexoVirt.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AlertsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public AlertsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AlertsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public AlertsApi(string basePath)
        {
            this.Configuration = NexoVirt.Sdk.Client.Configuration.MergeConfigurations(
                NexoVirt.Sdk.Client.GlobalConfiguration.Instance,
                new NexoVirt.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new NexoVirt.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = NexoVirt.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AlertsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public AlertsApi(NexoVirt.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = NexoVirt.Sdk.Client.Configuration.MergeConfigurations(
                NexoVirt.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new NexoVirt.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = NexoVirt.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AlertsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AlertsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AlertsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AlertsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = NexoVirt.Sdk.Client.Configuration.MergeConfigurations(
                NexoVirt.Sdk.Client.GlobalConfiguration.Instance,
                new NexoVirt.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new NexoVirt.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = NexoVirt.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AlertsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AlertsApi(HttpClient client, NexoVirt.Sdk.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = NexoVirt.Sdk.Client.Configuration.MergeConfigurations(
                NexoVirt.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new NexoVirt.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = NexoVirt.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AlertsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public AlertsApi(NexoVirt.Sdk.Client.ISynchronousClient client, NexoVirt.Sdk.Client.IAsynchronousClient asyncClient, NexoVirt.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = NexoVirt.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public NexoVirt.Sdk.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public NexoVirt.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public NexoVirt.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public NexoVirt.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public NexoVirt.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Acknowledge an alert 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId"></param>
        /// <returns>Envelope</returns>
        public Envelope AckAlert(int alertId)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = AckAlertWithHttpInfo(alertId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Acknowledge an alert 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId"></param>
        /// <returns>ApiResponse of Envelope</returns>
        public NexoVirt.Sdk.Client.ApiResponse<Envelope> AckAlertWithHttpInfo(int alertId)
        {
            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("alertId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(alertId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Envelope>("/alerts/{alertId}/ack", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AckAlert", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Acknowledge an alert 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        public async System.Threading.Tasks.Task<Envelope> AckAlertAsync(int alertId, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = await AckAlertWithHttpInfoAsync(alertId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Acknowledge an alert 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<Envelope>> AckAlertWithHttpInfoAsync(int alertId, System.Threading.CancellationToken cancellationToken = default)
        {

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("alertId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(alertId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Envelope>("/alerts/{alertId}/ack", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AckAlert", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create an alert rule 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAlertRuleRequest"></param>
        /// <returns>Envelope</returns>
        public Envelope CreateAlertRule(CreateAlertRuleRequest createAlertRuleRequest)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = CreateAlertRuleWithHttpInfo(createAlertRuleRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create an alert rule 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAlertRuleRequest"></param>
        /// <returns>ApiResponse of Envelope</returns>
        public NexoVirt.Sdk.Client.ApiResponse<Envelope> CreateAlertRuleWithHttpInfo(CreateAlertRuleRequest createAlertRuleRequest)
        {
            // verify the required parameter 'createAlertRuleRequest' is set
            if (createAlertRuleRequest == null)
                throw new NexoVirt.Sdk.Client.ApiException(400, "Missing required parameter 'createAlertRuleRequest' when calling AlertsApi->CreateAlertRule");

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createAlertRuleRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Envelope>("/alert-rules", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateAlertRule", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create an alert rule 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAlertRuleRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        public async System.Threading.Tasks.Task<Envelope> CreateAlertRuleAsync(CreateAlertRuleRequest createAlertRuleRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = await CreateAlertRuleWithHttpInfoAsync(createAlertRuleRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create an alert rule 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAlertRuleRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<Envelope>> CreateAlertRuleWithHttpInfoAsync(CreateAlertRuleRequest createAlertRuleRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createAlertRuleRequest' is set
            if (createAlertRuleRequest == null)
                throw new NexoVirt.Sdk.Client.ApiException(400, "Missing required parameter 'createAlertRuleRequest' when calling AlertsApi->CreateAlertRule");


            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createAlertRuleRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Envelope>("/alert-rules", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateAlertRule", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete an alert rule 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ruleId"></param>
        /// <returns>Envelope</returns>
        public Envelope DeleteAlertRule(int ruleId)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = DeleteAlertRuleWithHttpInfo(ruleId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete an alert rule 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ruleId"></param>
        /// <returns>ApiResponse of Envelope</returns>
        public NexoVirt.Sdk.Client.ApiResponse<Envelope> DeleteAlertRuleWithHttpInfo(int ruleId)
        {
            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("ruleId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(ruleId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Envelope>("/alert-rules/{ruleId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteAlertRule", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete an alert rule 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ruleId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        public async System.Threading.Tasks.Task<Envelope> DeleteAlertRuleAsync(int ruleId, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = await DeleteAlertRuleWithHttpInfoAsync(ruleId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete an alert rule 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ruleId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<Envelope>> DeleteAlertRuleWithHttpInfoAsync(int ruleId, System.Threading.CancellationToken cancellationToken = default)
        {

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("ruleId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(ruleId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Envelope>("/alert-rules/{ruleId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteAlertRule", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List alert rules 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>Envelope</returns>
        public Envelope ListAlertRules(int? page = default, int? perPage = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = ListAlertRulesWithHttpInfo(page, perPage);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List alert rules 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>ApiResponse of Envelope</returns>
        public NexoVirt.Sdk.Client.ApiResponse<Envelope> ListAlertRulesWithHttpInfo(int? page = default, int? perPage = default)
        {
            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "perPage", perPage));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Envelope>("/alert-rules", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListAlertRules", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List alert rules 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        public async System.Threading.Tasks.Task<Envelope> ListAlertRulesAsync(int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = await ListAlertRulesWithHttpInfoAsync(page, perPage, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List alert rules 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<Envelope>> ListAlertRulesWithHttpInfoAsync(int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default)
        {

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "perPage", perPage));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Envelope>("/alert-rules", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListAlertRules", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List alerts Alert instances, newest first, filterable by status and severity. Paginated.
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status"> (optional)</param>
        /// <param name="severity"> (optional)</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>Envelope</returns>
        public Envelope ListAlerts(string? status = default, string? severity = default, int? page = default, int? perPage = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = ListAlertsWithHttpInfo(status, severity, page, perPage);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List alerts Alert instances, newest first, filterable by status and severity. Paginated.
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status"> (optional)</param>
        /// <param name="severity"> (optional)</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>ApiResponse of Envelope</returns>
        public NexoVirt.Sdk.Client.ApiResponse<Envelope> ListAlertsWithHttpInfo(string? status = default, string? severity = default, int? page = default, int? perPage = default)
        {
            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }
            if (severity != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "severity", severity));
            }
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "perPage", perPage));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Envelope>("/alerts", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListAlerts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List alerts Alert instances, newest first, filterable by status and severity. Paginated.
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status"> (optional)</param>
        /// <param name="severity"> (optional)</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        public async System.Threading.Tasks.Task<Envelope> ListAlertsAsync(string? status = default, string? severity = default, int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = await ListAlertsWithHttpInfoAsync(status, severity, page, perPage, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List alerts Alert instances, newest first, filterable by status and severity. Paginated.
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="status"> (optional)</param>
        /// <param name="severity"> (optional)</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<Envelope>> ListAlertsWithHttpInfoAsync(string? status = default, string? severity = default, int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default)
        {

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }
            if (severity != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "severity", severity));
            }
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "perPage", perPage));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Envelope>("/alerts", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListAlerts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Resolve an alert 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId"></param>
        /// <returns>Envelope</returns>
        public Envelope ResolveAlert(int alertId)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = ResolveAlertWithHttpInfo(alertId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Resolve an alert 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId"></param>
        /// <returns>ApiResponse of Envelope</returns>
        public NexoVirt.Sdk.Client.ApiResponse<Envelope> ResolveAlertWithHttpInfo(int alertId)
        {
            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("alertId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(alertId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Envelope>("/alerts/{alertId}/resolve", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ResolveAlert", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Resolve an alert 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        public async System.Threading.Tasks.Task<Envelope> ResolveAlertAsync(int alertId, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = await ResolveAlertWithHttpInfoAsync(alertId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Resolve an alert 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="alertId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<Envelope>> ResolveAlertWithHttpInfoAsync(int alertId, System.Threading.CancellationToken cancellationToken = default)
        {

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("alertId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(alertId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Envelope>("/alerts/{alertId}/resolve", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ResolveAlert", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update an alert rule 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ruleId"></param>
        /// <param name="createAlertRuleRequest"></param>
        /// <returns>Envelope</returns>
        public Envelope UpdateAlertRule(int ruleId, CreateAlertRuleRequest createAlertRuleRequest)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = UpdateAlertRuleWithHttpInfo(ruleId, createAlertRuleRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update an alert rule 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ruleId"></param>
        /// <param name="createAlertRuleRequest"></param>
        /// <returns>ApiResponse of Envelope</returns>
        public NexoVirt.Sdk.Client.ApiResponse<Envelope> UpdateAlertRuleWithHttpInfo(int ruleId, CreateAlertRuleRequest createAlertRuleRequest)
        {
            // verify the required parameter 'createAlertRuleRequest' is set
            if (createAlertRuleRequest == null)
                throw new NexoVirt.Sdk.Client.ApiException(400, "Missing required parameter 'createAlertRuleRequest' when calling AlertsApi->UpdateAlertRule");

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("ruleId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(ruleId)); // path parameter
            localVarRequestOptions.Data = createAlertRuleRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Envelope>("/alert-rules/{ruleId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateAlertRule", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update an alert rule 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ruleId"></param>
        /// <param name="createAlertRuleRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        public async System.Threading.Tasks.Task<Envelope> UpdateAlertRuleAsync(int ruleId, CreateAlertRuleRequest createAlertRuleRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = await UpdateAlertRuleWithHttpInfoAsync(ruleId, createAlertRuleRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update an alert rule 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ruleId"></param>
        /// <param name="createAlertRuleRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<Envelope>> UpdateAlertRuleWithHttpInfoAsync(int ruleId, CreateAlertRuleRequest createAlertRuleRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createAlertRuleRequest' is set
            if (createAlertRuleRequest == null)
                throw new NexoVirt.Sdk.Client.ApiException(400, "Missing required parameter 'createAlertRuleRequest' when calling AlertsApi->UpdateAlertRule");


            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("ruleId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(ruleId)); // path parameter
            localVarRequestOptions.Data = createAlertRuleRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Envelope>("/alert-rules/{ruleId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateAlertRule", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
