/*
 * NexoVirt REST API
 *
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using NexoVirt.Sdk.Client;
using NexoVirt.Sdk.Model;

namespace NexoVirt.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INetworkingApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Apply NAT
        /// </summary>
        /// <remarks>
        /// Enqueues the constrained apply_nat agent job that writes the host&#39;s NAT rules from validated templates.
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <returns>Envelope</returns>
        Envelope ApplyNat(int hostId);

        /// <summary>
        /// Apply NAT
        /// </summary>
        /// <remarks>
        /// Enqueues the constrained apply_nat agent job that writes the host&#39;s NAT rules from validated templates.
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <returns>ApiResponse of Envelope</returns>
        ApiResponse<Envelope> ApplyNatWithHttpInfo(int hostId);
        /// <summary>
        /// Add a port-forward
        /// </summary>
        /// <remarks>
        /// Adds a DNAT port-forward. Validated fail-closed (dest IP must be inside the private CIDR).
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="createPortForwardRequest"></param>
        /// <returns>Envelope</returns>
        Envelope CreatePortForward(int hostId, CreatePortForwardRequest createPortForwardRequest);

        /// <summary>
        /// Add a port-forward
        /// </summary>
        /// <remarks>
        /// Adds a DNAT port-forward. Validated fail-closed (dest IP must be inside the private CIDR).
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="createPortForwardRequest"></param>
        /// <returns>ApiResponse of Envelope</returns>
        ApiResponse<Envelope> CreatePortForwardWithHttpInfo(int hostId, CreatePortForwardRequest createPortForwardRequest);
        /// <summary>
        /// Delete a port-forward
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="pfId"></param>
        /// <returns>Envelope</returns>
        Envelope DeletePortForward(int hostId, int pfId);

        /// <summary>
        /// Delete a port-forward
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="pfId"></param>
        /// <returns>ApiResponse of Envelope</returns>
        ApiResponse<Envelope> DeletePortForwardWithHttpInfo(int hostId, int pfId);
        /// <summary>
        /// Get NAT settings and port-forwards
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <returns>Envelope</returns>
        Envelope GetNat(int hostId);

        /// <summary>
        /// Get NAT settings and port-forwards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <returns>ApiResponse of Envelope</returns>
        ApiResponse<Envelope> GetNatWithHttpInfo(int hostId);
        /// <summary>
        /// Set NAT settings
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="setNatSettingsRequest"></param>
        /// <returns>Envelope</returns>
        Envelope SetNatSettings(int hostId, SetNatSettingsRequest setNatSettingsRequest);

        /// <summary>
        /// Set NAT settings
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="setNatSettingsRequest"></param>
        /// <returns>ApiResponse of Envelope</returns>
        ApiResponse<Envelope> SetNatSettingsWithHttpInfo(int hostId, SetNatSettingsRequest setNatSettingsRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INetworkingApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Apply NAT
        /// </summary>
        /// <remarks>
        /// Enqueues the constrained apply_nat agent job that writes the host&#39;s NAT rules from validated templates.
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        System.Threading.Tasks.Task<Envelope> ApplyNatAsync(int hostId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Apply NAT
        /// </summary>
        /// <remarks>
        /// Enqueues the constrained apply_nat agent job that writes the host&#39;s NAT rules from validated templates.
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<Envelope>> ApplyNatWithHttpInfoAsync(int hostId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Add a port-forward
        /// </summary>
        /// <remarks>
        /// Adds a DNAT port-forward. Validated fail-closed (dest IP must be inside the private CIDR).
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="createPortForwardRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        System.Threading.Tasks.Task<Envelope> CreatePortForwardAsync(int hostId, CreatePortForwardRequest createPortForwardRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Add a port-forward
        /// </summary>
        /// <remarks>
        /// Adds a DNAT port-forward. Validated fail-closed (dest IP must be inside the private CIDR).
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="createPortForwardRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<Envelope>> CreatePortForwardWithHttpInfoAsync(int hostId, CreatePortForwardRequest createPortForwardRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Delete a port-forward
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="pfId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        System.Threading.Tasks.Task<Envelope> DeletePortForwardAsync(int hostId, int pfId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete a port-forward
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="pfId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<Envelope>> DeletePortForwardWithHttpInfoAsync(int hostId, int pfId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get NAT settings and port-forwards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        System.Threading.Tasks.Task<Envelope> GetNatAsync(int hostId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get NAT settings and port-forwards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<Envelope>> GetNatWithHttpInfoAsync(int hostId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Set NAT settings
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="setNatSettingsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        System.Threading.Tasks.Task<Envelope> SetNatSettingsAsync(int hostId, SetNatSettingsRequest setNatSettingsRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Set NAT settings
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="setNatSettingsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<Envelope>> SetNatSettingsWithHttpInfoAsync(int hostId, SetNatSettingsRequest setNatSettingsRequest, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INetworkingApi : INetworkingApiSync, INetworkingApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class NetworkingApi : IDisposable, INetworkingApi
    {
        private NexoVirt.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkingApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public NetworkingApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkingApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public NetworkingApi(string basePath)
        {
            this.Configuration = NexoVirt.Sdk.Client.Configuration.MergeConfigurations(
                NexoVirt.Sdk.Client.GlobalConfiguration.Instance,
                new NexoVirt.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new NexoVirt.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = NexoVirt.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkingApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public NetworkingApi(NexoVirt.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = NexoVirt.Sdk.Client.Configuration.MergeConfigurations(
                NexoVirt.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new NexoVirt.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = NexoVirt.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkingApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public NetworkingApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkingApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public NetworkingApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = NexoVirt.Sdk.Client.Configuration.MergeConfigurations(
                NexoVirt.Sdk.Client.GlobalConfiguration.Instance,
                new NexoVirt.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new NexoVirt.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = NexoVirt.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkingApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public NetworkingApi(HttpClient client, NexoVirt.Sdk.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = NexoVirt.Sdk.Client.Configuration.MergeConfigurations(
                NexoVirt.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new NexoVirt.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = NexoVirt.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkingApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public NetworkingApi(NexoVirt.Sdk.Client.ISynchronousClient client, NexoVirt.Sdk.Client.IAsynchronousClient asyncClient, NexoVirt.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = NexoVirt.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public NexoVirt.Sdk.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public NexoVirt.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public NexoVirt.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public NexoVirt.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public NexoVirt.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Apply NAT Enqueues the constrained apply_nat agent job that writes the host&#39;s NAT rules from validated templates.
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <returns>Envelope</returns>
        public Envelope ApplyNat(int hostId)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = ApplyNatWithHttpInfo(hostId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Apply NAT Enqueues the constrained apply_nat agent job that writes the host&#39;s NAT rules from validated templates.
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <returns>ApiResponse of Envelope</returns>
        public NexoVirt.Sdk.Client.ApiResponse<Envelope> ApplyNatWithHttpInfo(int hostId)
        {
            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Envelope>("/hosts/{hostId}/nat/apply", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApplyNat", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Apply NAT Enqueues the constrained apply_nat agent job that writes the host&#39;s NAT rules from validated templates.
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        public async System.Threading.Tasks.Task<Envelope> ApplyNatAsync(int hostId, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = await ApplyNatWithHttpInfoAsync(hostId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Apply NAT Enqueues the constrained apply_nat agent job that writes the host&#39;s NAT rules from validated templates.
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<Envelope>> ApplyNatWithHttpInfoAsync(int hostId, System.Threading.CancellationToken cancellationToken = default)
        {

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Envelope>("/hosts/{hostId}/nat/apply", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApplyNat", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Add a port-forward Adds a DNAT port-forward. Validated fail-closed (dest IP must be inside the private CIDR).
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="createPortForwardRequest"></param>
        /// <returns>Envelope</returns>
        public Envelope CreatePortForward(int hostId, CreatePortForwardRequest createPortForwardRequest)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = CreatePortForwardWithHttpInfo(hostId, createPortForwardRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Add a port-forward Adds a DNAT port-forward. Validated fail-closed (dest IP must be inside the private CIDR).
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="createPortForwardRequest"></param>
        /// <returns>ApiResponse of Envelope</returns>
        public NexoVirt.Sdk.Client.ApiResponse<Envelope> CreatePortForwardWithHttpInfo(int hostId, CreatePortForwardRequest createPortForwardRequest)
        {
            // verify the required parameter 'createPortForwardRequest' is set
            if (createPortForwardRequest == null)
                throw new NexoVirt.Sdk.Client.ApiException(400, "Missing required parameter 'createPortForwardRequest' when calling NetworkingApi->CreatePortForward");

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter
            localVarRequestOptions.Data = createPortForwardRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Envelope>("/hosts/{hostId}/nat/port-forwards", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreatePortForward", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Add a port-forward Adds a DNAT port-forward. Validated fail-closed (dest IP must be inside the private CIDR).
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="createPortForwardRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        public async System.Threading.Tasks.Task<Envelope> CreatePortForwardAsync(int hostId, CreatePortForwardRequest createPortForwardRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = await CreatePortForwardWithHttpInfoAsync(hostId, createPortForwardRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Add a port-forward Adds a DNAT port-forward. Validated fail-closed (dest IP must be inside the private CIDR).
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="createPortForwardRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<Envelope>> CreatePortForwardWithHttpInfoAsync(int hostId, CreatePortForwardRequest createPortForwardRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createPortForwardRequest' is set
            if (createPortForwardRequest == null)
                throw new NexoVirt.Sdk.Client.ApiException(400, "Missing required parameter 'createPortForwardRequest' when calling NetworkingApi->CreatePortForward");


            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter
            localVarRequestOptions.Data = createPortForwardRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Envelope>("/hosts/{hostId}/nat/port-forwards", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreatePortForward", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete a port-forward 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="pfId"></param>
        /// <returns>Envelope</returns>
        public Envelope DeletePortForward(int hostId, int pfId)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = DeletePortForwardWithHttpInfo(hostId, pfId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete a port-forward 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="pfId"></param>
        /// <returns>ApiResponse of Envelope</returns>
        public NexoVirt.Sdk.Client.ApiResponse<Envelope> DeletePortForwardWithHttpInfo(int hostId, int pfId)
        {
            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter
            localVarRequestOptions.PathParameters.Add("pfId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(pfId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Envelope>("/hosts/{hostId}/nat/port-forwards/{pfId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeletePortForward", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete a port-forward 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="pfId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        public async System.Threading.Tasks.Task<Envelope> DeletePortForwardAsync(int hostId, int pfId, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = await DeletePortForwardWithHttpInfoAsync(hostId, pfId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete a port-forward 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="pfId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<Envelope>> DeletePortForwardWithHttpInfoAsync(int hostId, int pfId, System.Threading.CancellationToken cancellationToken = default)
        {

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter
            localVarRequestOptions.PathParameters.Add("pfId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(pfId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Envelope>("/hosts/{hostId}/nat/port-forwards/{pfId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeletePortForward", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get NAT settings and port-forwards 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <returns>Envelope</returns>
        public Envelope GetNat(int hostId)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = GetNatWithHttpInfo(hostId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get NAT settings and port-forwards 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <returns>ApiResponse of Envelope</returns>
        public NexoVirt.Sdk.Client.ApiResponse<Envelope> GetNatWithHttpInfo(int hostId)
        {
            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Envelope>("/hosts/{hostId}/nat", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetNat", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get NAT settings and port-forwards 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        public async System.Threading.Tasks.Task<Envelope> GetNatAsync(int hostId, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = await GetNatWithHttpInfoAsync(hostId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get NAT settings and port-forwards 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<Envelope>> GetNatWithHttpInfoAsync(int hostId, System.Threading.CancellationToken cancellationToken = default)
        {

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Envelope>("/hosts/{hostId}/nat", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetNat", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Set NAT settings 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="setNatSettingsRequest"></param>
        /// <returns>Envelope</returns>
        public Envelope SetNatSettings(int hostId, SetNatSettingsRequest setNatSettingsRequest)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = SetNatSettingsWithHttpInfo(hostId, setNatSettingsRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Set NAT settings 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="setNatSettingsRequest"></param>
        /// <returns>ApiResponse of Envelope</returns>
        public NexoVirt.Sdk.Client.ApiResponse<Envelope> SetNatSettingsWithHttpInfo(int hostId, SetNatSettingsRequest setNatSettingsRequest)
        {
            // verify the required parameter 'setNatSettingsRequest' is set
            if (setNatSettingsRequest == null)
                throw new NexoVirt.Sdk.Client.ApiException(400, "Missing required parameter 'setNatSettingsRequest' when calling NetworkingApi->SetNatSettings");

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter
            localVarRequestOptions.Data = setNatSettingsRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Envelope>("/hosts/{hostId}/nat", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SetNatSettings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Set NAT settings 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="setNatSettingsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        public async System.Threading.Tasks.Task<Envelope> SetNatSettingsAsync(int hostId, SetNatSettingsRequest setNatSettingsRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<Envelope> localVarResponse = await SetNatSettingsWithHttpInfoAsync(hostId, setNatSettingsRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Set NAT settings 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="setNatSettingsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<Envelope>> SetNatSettingsWithHttpInfoAsync(int hostId, SetNatSettingsRequest setNatSettingsRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'setNatSettingsRequest' is set
            if (setNatSettingsRequest == null)
                throw new NexoVirt.Sdk.Client.ApiException(400, "Missing required parameter 'setNatSettingsRequest' when calling NetworkingApi->SetNatSettings");


            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter
            localVarRequestOptions.Data = setNatSettingsRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Envelope>("/hosts/{hostId}/nat", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SetNatSettings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
