/*
 * NexoVirt REST API
 *
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using NexoVirt.Sdk.Client;
using NexoVirt.Sdk.Model;

namespace NexoVirt.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProvisioningDiscoveryApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get the next free VMID
        /// </summary>
        /// <remarks>
        /// A free VMID from the live PVE &#x60;cluster/nextid&#x60; call. Create still requires an explicit &#x60;vmid&#x60; in the body; use this to obtain one. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <returns>GetNextVmid200Response</returns>
        GetNextVmid200Response GetNextVmid(int hostId);

        /// <summary>
        /// Get the next free VMID
        /// </summary>
        /// <remarks>
        /// A free VMID from the live PVE &#x60;cluster/nextid&#x60; call. Create still requires an explicit &#x60;vmid&#x60; in the body; use this to obtain one. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <returns>ApiResponse of GetNextVmid200Response</returns>
        ApiResponse<GetNextVmid200Response> GetNextVmidWithHttpInfo(int hostId);
        /// <summary>
        /// List LXC container templates
        /// </summary>
        /// <remarks>
        /// LXC template options. &#x60;managed&#x60; is the panel&#39;s own CT template library (&#x60;lxc_template_id&#x60; is the create argument, staged on demand). &#x60;available&#x60; is live PVE &#x60;vztmpl&#x60; volumes on &#x60;?node&#x60; (only populated when a valid &#x60;node&#x60; is given; &#x60;volid&#x60; is the create argument). Without &#x60;?node&#x60;, &#x60;available&#x60; is an empty array and no PVE call is made. Not paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="node">Restrict results to this PVE node (plus any datacenter-wide/shared entries). (optional)</param>
        /// <returns>ListCtTemplates200Response</returns>
        ListCtTemplates200Response ListCtTemplates(int hostId, string? node = default);

        /// <summary>
        /// List LXC container templates
        /// </summary>
        /// <remarks>
        /// LXC template options. &#x60;managed&#x60; is the panel&#39;s own CT template library (&#x60;lxc_template_id&#x60; is the create argument, staged on demand). &#x60;available&#x60; is live PVE &#x60;vztmpl&#x60; volumes on &#x60;?node&#x60; (only populated when a valid &#x60;node&#x60; is given; &#x60;volid&#x60; is the create argument). Without &#x60;?node&#x60;, &#x60;available&#x60; is an empty array and no PVE call is made. Not paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="node">Restrict results to this PVE node (plus any datacenter-wide/shared entries). (optional)</param>
        /// <returns>ApiResponse of ListCtTemplates200Response</returns>
        ApiResponse<ListCtTemplates200Response> ListCtTemplatesWithHttpInfo(int hostId, string? node = default);
        /// <summary>
        /// List IP zones
        /// </summary>
        /// <remarks>
        /// The host&#39;s IP zones (IPAM). &#x60;ref&#x60; (for example &#x60;zone:3&#x60;) is the exact &#x60;ip_source&#x60; create value; using it allocates a static IP from the zone&#39;s pool. Paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>ListIpZones200Response</returns>
        ListIpZones200Response ListIpZones(int hostId, int? page = default, int? perPage = default);

        /// <summary>
        /// List IP zones
        /// </summary>
        /// <remarks>
        /// The host&#39;s IP zones (IPAM). &#x60;ref&#x60; (for example &#x60;zone:3&#x60;) is the exact &#x60;ip_source&#x60; create value; using it allocates a static IP from the zone&#39;s pool. Paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>ApiResponse of ListIpZones200Response</returns>
        ApiResponse<ListIpZones200Response> ListIpZonesWithHttpInfo(int hostId, int? page = default, int? perPage = default);
        /// <summary>
        /// List QEMU OS templates
        /// </summary>
        /// <remarks>
        /// Cloud-init OS templates for QEMU. &#x60;ref&#x60; (for example &#x60;tpl:7&#x60;) is the exact &#x60;os_template&#x60; value to send at create. Never returns SSH keys or other cloud-init secrets. Paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>ListOsTemplates200Response</returns>
        ListOsTemplates200Response ListOsTemplates(int hostId, int? page = default, int? perPage = default);

        /// <summary>
        /// List QEMU OS templates
        /// </summary>
        /// <remarks>
        /// Cloud-init OS templates for QEMU. &#x60;ref&#x60; (for example &#x60;tpl:7&#x60;) is the exact &#x60;os_template&#x60; value to send at create. Never returns SSH keys or other cloud-init secrets. Paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>ApiResponse of ListOsTemplates200Response</returns>
        ApiResponse<ListOsTemplates200Response> ListOsTemplatesWithHttpInfo(int hostId, int? page = default, int? perPage = default);
        /// <summary>
        /// List resource plans
        /// </summary>
        /// <remarks>
        /// Active resource plans usable as &#x60;plan_id&#x60; at create time. A plan fills and locks &#x60;cores&#x60;, &#x60;memory_mb&#x60;, and &#x60;disk_gb&#x60; on the created guest. Paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>ListPlans200Response</returns>
        ListPlans200Response ListPlans(int hostId, int? page = default, int? perPage = default);

        /// <summary>
        /// List resource plans
        /// </summary>
        /// <remarks>
        /// Active resource plans usable as &#x60;plan_id&#x60; at create time. A plan fills and locks &#x60;cores&#x60;, &#x60;memory_mb&#x60;, and &#x60;disk_gb&#x60; on the created guest. Paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>ApiResponse of ListPlans200Response</returns>
        ApiResponse<ListPlans200Response> ListPlansWithHttpInfo(int hostId, int? page = default, int? perPage = default);
        /// <summary>
        /// List a user&#39;s SSH keys
        /// </summary>
        /// <remarks>
        /// A user&#39;s stored SSH keys, exposing only &#x60;id&#x60;, &#x60;name&#x60;, and &#x60;fingerprint&#x60;, never the key body. Pass the owner&#39;s id as &#x60;owner_id&#x60; at create to auto-inject all of that user&#39;s stored keys. Not paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <returns>ListUserSshKeys200Response</returns>
        ListUserSshKeys200Response ListUserSshKeys(int userId);

        /// <summary>
        /// List a user&#39;s SSH keys
        /// </summary>
        /// <remarks>
        /// A user&#39;s stored SSH keys, exposing only &#x60;id&#x60;, &#x60;name&#x60;, and &#x60;fingerprint&#x60;, never the key body. Pass the owner&#39;s id as &#x60;owner_id&#x60; at create to auto-inject all of that user&#39;s stored keys. Not paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <returns>ApiResponse of ListUserSshKeys200Response</returns>
        ApiResponse<ListUserSshKeys200Response> ListUserSshKeysWithHttpInfo(int userId);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProvisioningDiscoveryApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get the next free VMID
        /// </summary>
        /// <remarks>
        /// A free VMID from the live PVE &#x60;cluster/nextid&#x60; call. Create still requires an explicit &#x60;vmid&#x60; in the body; use this to obtain one. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetNextVmid200Response</returns>
        System.Threading.Tasks.Task<GetNextVmid200Response> GetNextVmidAsync(int hostId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get the next free VMID
        /// </summary>
        /// <remarks>
        /// A free VMID from the live PVE &#x60;cluster/nextid&#x60; call. Create still requires an explicit &#x60;vmid&#x60; in the body; use this to obtain one. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetNextVmid200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetNextVmid200Response>> GetNextVmidWithHttpInfoAsync(int hostId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List LXC container templates
        /// </summary>
        /// <remarks>
        /// LXC template options. &#x60;managed&#x60; is the panel&#39;s own CT template library (&#x60;lxc_template_id&#x60; is the create argument, staged on demand). &#x60;available&#x60; is live PVE &#x60;vztmpl&#x60; volumes on &#x60;?node&#x60; (only populated when a valid &#x60;node&#x60; is given; &#x60;volid&#x60; is the create argument). Without &#x60;?node&#x60;, &#x60;available&#x60; is an empty array and no PVE call is made. Not paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="node">Restrict results to this PVE node (plus any datacenter-wide/shared entries). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListCtTemplates200Response</returns>
        System.Threading.Tasks.Task<ListCtTemplates200Response> ListCtTemplatesAsync(int hostId, string? node = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List LXC container templates
        /// </summary>
        /// <remarks>
        /// LXC template options. &#x60;managed&#x60; is the panel&#39;s own CT template library (&#x60;lxc_template_id&#x60; is the create argument, staged on demand). &#x60;available&#x60; is live PVE &#x60;vztmpl&#x60; volumes on &#x60;?node&#x60; (only populated when a valid &#x60;node&#x60; is given; &#x60;volid&#x60; is the create argument). Without &#x60;?node&#x60;, &#x60;available&#x60; is an empty array and no PVE call is made. Not paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="node">Restrict results to this PVE node (plus any datacenter-wide/shared entries). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListCtTemplates200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListCtTemplates200Response>> ListCtTemplatesWithHttpInfoAsync(int hostId, string? node = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List IP zones
        /// </summary>
        /// <remarks>
        /// The host&#39;s IP zones (IPAM). &#x60;ref&#x60; (for example &#x60;zone:3&#x60;) is the exact &#x60;ip_source&#x60; create value; using it allocates a static IP from the zone&#39;s pool. Paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListIpZones200Response</returns>
        System.Threading.Tasks.Task<ListIpZones200Response> ListIpZonesAsync(int hostId, int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List IP zones
        /// </summary>
        /// <remarks>
        /// The host&#39;s IP zones (IPAM). &#x60;ref&#x60; (for example &#x60;zone:3&#x60;) is the exact &#x60;ip_source&#x60; create value; using it allocates a static IP from the zone&#39;s pool. Paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListIpZones200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListIpZones200Response>> ListIpZonesWithHttpInfoAsync(int hostId, int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List QEMU OS templates
        /// </summary>
        /// <remarks>
        /// Cloud-init OS templates for QEMU. &#x60;ref&#x60; (for example &#x60;tpl:7&#x60;) is the exact &#x60;os_template&#x60; value to send at create. Never returns SSH keys or other cloud-init secrets. Paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListOsTemplates200Response</returns>
        System.Threading.Tasks.Task<ListOsTemplates200Response> ListOsTemplatesAsync(int hostId, int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List QEMU OS templates
        /// </summary>
        /// <remarks>
        /// Cloud-init OS templates for QEMU. &#x60;ref&#x60; (for example &#x60;tpl:7&#x60;) is the exact &#x60;os_template&#x60; value to send at create. Never returns SSH keys or other cloud-init secrets. Paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListOsTemplates200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListOsTemplates200Response>> ListOsTemplatesWithHttpInfoAsync(int hostId, int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List resource plans
        /// </summary>
        /// <remarks>
        /// Active resource plans usable as &#x60;plan_id&#x60; at create time. A plan fills and locks &#x60;cores&#x60;, &#x60;memory_mb&#x60;, and &#x60;disk_gb&#x60; on the created guest. Paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListPlans200Response</returns>
        System.Threading.Tasks.Task<ListPlans200Response> ListPlansAsync(int hostId, int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List resource plans
        /// </summary>
        /// <remarks>
        /// Active resource plans usable as &#x60;plan_id&#x60; at create time. A plan fills and locks &#x60;cores&#x60;, &#x60;memory_mb&#x60;, and &#x60;disk_gb&#x60; on the created guest. Paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListPlans200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListPlans200Response>> ListPlansWithHttpInfoAsync(int hostId, int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List a user&#39;s SSH keys
        /// </summary>
        /// <remarks>
        /// A user&#39;s stored SSH keys, exposing only &#x60;id&#x60;, &#x60;name&#x60;, and &#x60;fingerprint&#x60;, never the key body. Pass the owner&#39;s id as &#x60;owner_id&#x60; at create to auto-inject all of that user&#39;s stored keys. Not paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListUserSshKeys200Response</returns>
        System.Threading.Tasks.Task<ListUserSshKeys200Response> ListUserSshKeysAsync(int userId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List a user&#39;s SSH keys
        /// </summary>
        /// <remarks>
        /// A user&#39;s stored SSH keys, exposing only &#x60;id&#x60;, &#x60;name&#x60;, and &#x60;fingerprint&#x60;, never the key body. Pass the owner&#39;s id as &#x60;owner_id&#x60; at create to auto-inject all of that user&#39;s stored keys. Not paginated. 
        /// </remarks>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListUserSshKeys200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListUserSshKeys200Response>> ListUserSshKeysWithHttpInfoAsync(int userId, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProvisioningDiscoveryApi : IProvisioningDiscoveryApiSync, IProvisioningDiscoveryApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ProvisioningDiscoveryApi : IDisposable, IProvisioningDiscoveryApi
    {
        private NexoVirt.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ProvisioningDiscoveryApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public ProvisioningDiscoveryApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProvisioningDiscoveryApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public ProvisioningDiscoveryApi(string basePath)
        {
            this.Configuration = NexoVirt.Sdk.Client.Configuration.MergeConfigurations(
                NexoVirt.Sdk.Client.GlobalConfiguration.Instance,
                new NexoVirt.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new NexoVirt.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = NexoVirt.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProvisioningDiscoveryApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public ProvisioningDiscoveryApi(NexoVirt.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = NexoVirt.Sdk.Client.Configuration.MergeConfigurations(
                NexoVirt.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new NexoVirt.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = NexoVirt.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProvisioningDiscoveryApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ProvisioningDiscoveryApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProvisioningDiscoveryApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ProvisioningDiscoveryApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = NexoVirt.Sdk.Client.Configuration.MergeConfigurations(
                NexoVirt.Sdk.Client.GlobalConfiguration.Instance,
                new NexoVirt.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new NexoVirt.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = NexoVirt.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProvisioningDiscoveryApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ProvisioningDiscoveryApi(HttpClient client, NexoVirt.Sdk.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = NexoVirt.Sdk.Client.Configuration.MergeConfigurations(
                NexoVirt.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new NexoVirt.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = NexoVirt.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProvisioningDiscoveryApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ProvisioningDiscoveryApi(NexoVirt.Sdk.Client.ISynchronousClient client, NexoVirt.Sdk.Client.IAsynchronousClient asyncClient, NexoVirt.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = NexoVirt.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public NexoVirt.Sdk.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public NexoVirt.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public NexoVirt.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public NexoVirt.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public NexoVirt.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get the next free VMID A free VMID from the live PVE &#x60;cluster/nextid&#x60; call. Create still requires an explicit &#x60;vmid&#x60; in the body; use this to obtain one. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <returns>GetNextVmid200Response</returns>
        public GetNextVmid200Response GetNextVmid(int hostId)
        {
            NexoVirt.Sdk.Client.ApiResponse<GetNextVmid200Response> localVarResponse = GetNextVmidWithHttpInfo(hostId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get the next free VMID A free VMID from the live PVE &#x60;cluster/nextid&#x60; call. Create still requires an explicit &#x60;vmid&#x60; in the body; use this to obtain one. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <returns>ApiResponse of GetNextVmid200Response</returns>
        public NexoVirt.Sdk.Client.ApiResponse<GetNextVmid200Response> GetNextVmidWithHttpInfo(int hostId)
        {
            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetNextVmid200Response>("/hosts/{hostId}/next-vmid", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetNextVmid", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get the next free VMID A free VMID from the live PVE &#x60;cluster/nextid&#x60; call. Create still requires an explicit &#x60;vmid&#x60; in the body; use this to obtain one. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetNextVmid200Response</returns>
        public async System.Threading.Tasks.Task<GetNextVmid200Response> GetNextVmidAsync(int hostId, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<GetNextVmid200Response> localVarResponse = await GetNextVmidWithHttpInfoAsync(hostId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get the next free VMID A free VMID from the live PVE &#x60;cluster/nextid&#x60; call. Create still requires an explicit &#x60;vmid&#x60; in the body; use this to obtain one. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetNextVmid200Response)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<GetNextVmid200Response>> GetNextVmidWithHttpInfoAsync(int hostId, System.Threading.CancellationToken cancellationToken = default)
        {

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetNextVmid200Response>("/hosts/{hostId}/next-vmid", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetNextVmid", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List LXC container templates LXC template options. &#x60;managed&#x60; is the panel&#39;s own CT template library (&#x60;lxc_template_id&#x60; is the create argument, staged on demand). &#x60;available&#x60; is live PVE &#x60;vztmpl&#x60; volumes on &#x60;?node&#x60; (only populated when a valid &#x60;node&#x60; is given; &#x60;volid&#x60; is the create argument). Without &#x60;?node&#x60;, &#x60;available&#x60; is an empty array and no PVE call is made. Not paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="node">Restrict results to this PVE node (plus any datacenter-wide/shared entries). (optional)</param>
        /// <returns>ListCtTemplates200Response</returns>
        public ListCtTemplates200Response ListCtTemplates(int hostId, string? node = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<ListCtTemplates200Response> localVarResponse = ListCtTemplatesWithHttpInfo(hostId, node);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List LXC container templates LXC template options. &#x60;managed&#x60; is the panel&#39;s own CT template library (&#x60;lxc_template_id&#x60; is the create argument, staged on demand). &#x60;available&#x60; is live PVE &#x60;vztmpl&#x60; volumes on &#x60;?node&#x60; (only populated when a valid &#x60;node&#x60; is given; &#x60;volid&#x60; is the create argument). Without &#x60;?node&#x60;, &#x60;available&#x60; is an empty array and no PVE call is made. Not paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="node">Restrict results to this PVE node (plus any datacenter-wide/shared entries). (optional)</param>
        /// <returns>ApiResponse of ListCtTemplates200Response</returns>
        public NexoVirt.Sdk.Client.ApiResponse<ListCtTemplates200Response> ListCtTemplatesWithHttpInfo(int hostId, string? node = default)
        {
            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter
            if (node != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "node", node));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListCtTemplates200Response>("/hosts/{hostId}/ct-templates", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListCtTemplates", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List LXC container templates LXC template options. &#x60;managed&#x60; is the panel&#39;s own CT template library (&#x60;lxc_template_id&#x60; is the create argument, staged on demand). &#x60;available&#x60; is live PVE &#x60;vztmpl&#x60; volumes on &#x60;?node&#x60; (only populated when a valid &#x60;node&#x60; is given; &#x60;volid&#x60; is the create argument). Without &#x60;?node&#x60;, &#x60;available&#x60; is an empty array and no PVE call is made. Not paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="node">Restrict results to this PVE node (plus any datacenter-wide/shared entries). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListCtTemplates200Response</returns>
        public async System.Threading.Tasks.Task<ListCtTemplates200Response> ListCtTemplatesAsync(int hostId, string? node = default, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<ListCtTemplates200Response> localVarResponse = await ListCtTemplatesWithHttpInfoAsync(hostId, node, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List LXC container templates LXC template options. &#x60;managed&#x60; is the panel&#39;s own CT template library (&#x60;lxc_template_id&#x60; is the create argument, staged on demand). &#x60;available&#x60; is live PVE &#x60;vztmpl&#x60; volumes on &#x60;?node&#x60; (only populated when a valid &#x60;node&#x60; is given; &#x60;volid&#x60; is the create argument). Without &#x60;?node&#x60;, &#x60;available&#x60; is an empty array and no PVE call is made. Not paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="node">Restrict results to this PVE node (plus any datacenter-wide/shared entries). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListCtTemplates200Response)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<ListCtTemplates200Response>> ListCtTemplatesWithHttpInfoAsync(int hostId, string? node = default, System.Threading.CancellationToken cancellationToken = default)
        {

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter
            if (node != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "node", node));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListCtTemplates200Response>("/hosts/{hostId}/ct-templates", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListCtTemplates", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List IP zones The host&#39;s IP zones (IPAM). &#x60;ref&#x60; (for example &#x60;zone:3&#x60;) is the exact &#x60;ip_source&#x60; create value; using it allocates a static IP from the zone&#39;s pool. Paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>ListIpZones200Response</returns>
        public ListIpZones200Response ListIpZones(int hostId, int? page = default, int? perPage = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<ListIpZones200Response> localVarResponse = ListIpZonesWithHttpInfo(hostId, page, perPage);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List IP zones The host&#39;s IP zones (IPAM). &#x60;ref&#x60; (for example &#x60;zone:3&#x60;) is the exact &#x60;ip_source&#x60; create value; using it allocates a static IP from the zone&#39;s pool. Paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>ApiResponse of ListIpZones200Response</returns>
        public NexoVirt.Sdk.Client.ApiResponse<ListIpZones200Response> ListIpZonesWithHttpInfo(int hostId, int? page = default, int? perPage = default)
        {
            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "perPage", perPage));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListIpZones200Response>("/hosts/{hostId}/ip-zones", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListIpZones", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List IP zones The host&#39;s IP zones (IPAM). &#x60;ref&#x60; (for example &#x60;zone:3&#x60;) is the exact &#x60;ip_source&#x60; create value; using it allocates a static IP from the zone&#39;s pool. Paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListIpZones200Response</returns>
        public async System.Threading.Tasks.Task<ListIpZones200Response> ListIpZonesAsync(int hostId, int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<ListIpZones200Response> localVarResponse = await ListIpZonesWithHttpInfoAsync(hostId, page, perPage, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List IP zones The host&#39;s IP zones (IPAM). &#x60;ref&#x60; (for example &#x60;zone:3&#x60;) is the exact &#x60;ip_source&#x60; create value; using it allocates a static IP from the zone&#39;s pool. Paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListIpZones200Response)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<ListIpZones200Response>> ListIpZonesWithHttpInfoAsync(int hostId, int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default)
        {

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "perPage", perPage));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListIpZones200Response>("/hosts/{hostId}/ip-zones", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListIpZones", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List QEMU OS templates Cloud-init OS templates for QEMU. &#x60;ref&#x60; (for example &#x60;tpl:7&#x60;) is the exact &#x60;os_template&#x60; value to send at create. Never returns SSH keys or other cloud-init secrets. Paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>ListOsTemplates200Response</returns>
        public ListOsTemplates200Response ListOsTemplates(int hostId, int? page = default, int? perPage = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<ListOsTemplates200Response> localVarResponse = ListOsTemplatesWithHttpInfo(hostId, page, perPage);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List QEMU OS templates Cloud-init OS templates for QEMU. &#x60;ref&#x60; (for example &#x60;tpl:7&#x60;) is the exact &#x60;os_template&#x60; value to send at create. Never returns SSH keys or other cloud-init secrets. Paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>ApiResponse of ListOsTemplates200Response</returns>
        public NexoVirt.Sdk.Client.ApiResponse<ListOsTemplates200Response> ListOsTemplatesWithHttpInfo(int hostId, int? page = default, int? perPage = default)
        {
            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "perPage", perPage));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListOsTemplates200Response>("/hosts/{hostId}/os-templates", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListOsTemplates", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List QEMU OS templates Cloud-init OS templates for QEMU. &#x60;ref&#x60; (for example &#x60;tpl:7&#x60;) is the exact &#x60;os_template&#x60; value to send at create. Never returns SSH keys or other cloud-init secrets. Paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListOsTemplates200Response</returns>
        public async System.Threading.Tasks.Task<ListOsTemplates200Response> ListOsTemplatesAsync(int hostId, int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<ListOsTemplates200Response> localVarResponse = await ListOsTemplatesWithHttpInfoAsync(hostId, page, perPage, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List QEMU OS templates Cloud-init OS templates for QEMU. &#x60;ref&#x60; (for example &#x60;tpl:7&#x60;) is the exact &#x60;os_template&#x60; value to send at create. Never returns SSH keys or other cloud-init secrets. Paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListOsTemplates200Response)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<ListOsTemplates200Response>> ListOsTemplatesWithHttpInfoAsync(int hostId, int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default)
        {

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "perPage", perPage));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListOsTemplates200Response>("/hosts/{hostId}/os-templates", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListOsTemplates", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List resource plans Active resource plans usable as &#x60;plan_id&#x60; at create time. A plan fills and locks &#x60;cores&#x60;, &#x60;memory_mb&#x60;, and &#x60;disk_gb&#x60; on the created guest. Paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>ListPlans200Response</returns>
        public ListPlans200Response ListPlans(int hostId, int? page = default, int? perPage = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<ListPlans200Response> localVarResponse = ListPlansWithHttpInfo(hostId, page, perPage);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List resource plans Active resource plans usable as &#x60;plan_id&#x60; at create time. A plan fills and locks &#x60;cores&#x60;, &#x60;memory_mb&#x60;, and &#x60;disk_gb&#x60; on the created guest. Paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <returns>ApiResponse of ListPlans200Response</returns>
        public NexoVirt.Sdk.Client.ApiResponse<ListPlans200Response> ListPlansWithHttpInfo(int hostId, int? page = default, int? perPage = default)
        {
            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "perPage", perPage));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListPlans200Response>("/hosts/{hostId}/plans", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListPlans", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List resource plans Active resource plans usable as &#x60;plan_id&#x60; at create time. A plan fills and locks &#x60;cores&#x60;, &#x60;memory_mb&#x60;, and &#x60;disk_gb&#x60; on the created guest. Paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListPlans200Response</returns>
        public async System.Threading.Tasks.Task<ListPlans200Response> ListPlansAsync(int hostId, int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<ListPlans200Response> localVarResponse = await ListPlansWithHttpInfoAsync(hostId, page, perPage, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List resource plans Active resource plans usable as &#x60;plan_id&#x60; at create time. A plan fills and locks &#x60;cores&#x60;, &#x60;memory_mb&#x60;, and &#x60;disk_gb&#x60; on the created guest. Paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostId">The panel&#39;s internal host id (from &#x60;GET /hosts&#x60;).</param>
        /// <param name="page">Page number, 1-based. (optional, default to 1)</param>
        /// <param name="perPage">Items per page, clamped to 1..200. (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListPlans200Response)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<ListPlans200Response>> ListPlansWithHttpInfoAsync(int hostId, int? page = default, int? perPage = default, System.Threading.CancellationToken cancellationToken = default)
        {

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("hostId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(hostId)); // path parameter
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(NexoVirt.Sdk.Client.ClientUtils.ParameterToMultiMap("", "perPage", perPage));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListPlans200Response>("/hosts/{hostId}/plans", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListPlans", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List a user&#39;s SSH keys A user&#39;s stored SSH keys, exposing only &#x60;id&#x60;, &#x60;name&#x60;, and &#x60;fingerprint&#x60;, never the key body. Pass the owner&#39;s id as &#x60;owner_id&#x60; at create to auto-inject all of that user&#39;s stored keys. Not paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <returns>ListUserSshKeys200Response</returns>
        public ListUserSshKeys200Response ListUserSshKeys(int userId)
        {
            NexoVirt.Sdk.Client.ApiResponse<ListUserSshKeys200Response> localVarResponse = ListUserSshKeysWithHttpInfo(userId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List a user&#39;s SSH keys A user&#39;s stored SSH keys, exposing only &#x60;id&#x60;, &#x60;name&#x60;, and &#x60;fingerprint&#x60;, never the key body. Pass the owner&#39;s id as &#x60;owner_id&#x60; at create to auto-inject all of that user&#39;s stored keys. Not paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <returns>ApiResponse of ListUserSshKeys200Response</returns>
        public NexoVirt.Sdk.Client.ApiResponse<ListUserSshKeys200Response> ListUserSshKeysWithHttpInfo(int userId)
        {
            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("userId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(userId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListUserSshKeys200Response>("/users/{userId}/ssh-keys", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListUserSshKeys", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List a user&#39;s SSH keys A user&#39;s stored SSH keys, exposing only &#x60;id&#x60;, &#x60;name&#x60;, and &#x60;fingerprint&#x60;, never the key body. Pass the owner&#39;s id as &#x60;owner_id&#x60; at create to auto-inject all of that user&#39;s stored keys. Not paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListUserSshKeys200Response</returns>
        public async System.Threading.Tasks.Task<ListUserSshKeys200Response> ListUserSshKeysAsync(int userId, System.Threading.CancellationToken cancellationToken = default)
        {
            NexoVirt.Sdk.Client.ApiResponse<ListUserSshKeys200Response> localVarResponse = await ListUserSshKeysWithHttpInfoAsync(userId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List a user&#39;s SSH keys A user&#39;s stored SSH keys, exposing only &#x60;id&#x60;, &#x60;name&#x60;, and &#x60;fingerprint&#x60;, never the key body. Pass the owner&#39;s id as &#x60;owner_id&#x60; at create to auto-inject all of that user&#39;s stored keys. Not paginated. 
        /// </summary>
        /// <exception cref="NexoVirt.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListUserSshKeys200Response)</returns>
        public async System.Threading.Tasks.Task<NexoVirt.Sdk.Client.ApiResponse<ListUserSshKeys200Response>> ListUserSshKeysWithHttpInfoAsync(int userId, System.Threading.CancellationToken cancellationToken = default)
        {

            NexoVirt.Sdk.Client.RequestOptions localVarRequestOptions = new NexoVirt.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = NexoVirt.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("userId", NexoVirt.Sdk.Client.ClientUtils.ParameterToString(userId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListUserSshKeys200Response>("/users/{userId}/ssh-keys", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListUserSshKeys", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
