/*
 * NexoVirt REST API
 *
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NexoVirt.Sdk.Model;
using NexoVirt.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NexoVirt.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing GuestCreateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GuestCreateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GuestCreateRequest
        //private GuestCreateRequest instance;

        public GuestCreateRequestTests()
        {
            // TODO uncomment below to create an instance of GuestCreateRequest
            //instance = new GuestCreateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GuestCreateRequest
        /// </summary>
        [Fact]
        public void GuestCreateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GuestCreateRequest
            //Assert.IsType<GuestCreateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Node'
        /// </summary>
        [Fact]
        public void NodeTest()
        {
            // TODO unit test for the property 'Node'
        }

        /// <summary>
        /// Test the property 'Vmid'
        /// </summary>
        [Fact]
        public void VmidTest()
        {
            // TODO unit test for the property 'Vmid'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'PlanId'
        /// </summary>
        [Fact]
        public void PlanIdTest()
        {
            // TODO unit test for the property 'PlanId'
        }

        /// <summary>
        /// Test the property 'Cores'
        /// </summary>
        [Fact]
        public void CoresTest()
        {
            // TODO unit test for the property 'Cores'
        }

        /// <summary>
        /// Test the property 'MemoryMb'
        /// </summary>
        [Fact]
        public void MemoryMbTest()
        {
            // TODO unit test for the property 'MemoryMb'
        }

        /// <summary>
        /// Test the property 'DiskGb'
        /// </summary>
        [Fact]
        public void DiskGbTest()
        {
            // TODO unit test for the property 'DiskGb'
        }

        /// <summary>
        /// Test the property 'Storage'
        /// </summary>
        [Fact]
        public void StorageTest()
        {
            // TODO unit test for the property 'Storage'
        }

        /// <summary>
        /// Test the property 'Bridge'
        /// </summary>
        [Fact]
        public void BridgeTest()
        {
            // TODO unit test for the property 'Bridge'
        }

        /// <summary>
        /// Test the property 'OsTemplate'
        /// </summary>
        [Fact]
        public void OsTemplateTest()
        {
            // TODO unit test for the property 'OsTemplate'
        }

        /// <summary>
        /// Test the property 'LxcTemplateId'
        /// </summary>
        [Fact]
        public void LxcTemplateIdTest()
        {
            // TODO unit test for the property 'LxcTemplateId'
        }

        /// <summary>
        /// Test the property 'IpSource'
        /// </summary>
        [Fact]
        public void IpSourceTest()
        {
            // TODO unit test for the property 'IpSource'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'SshKeys'
        /// </summary>
        [Fact]
        public void SshKeysTest()
        {
            // TODO unit test for the property 'SshKeys'
        }

        /// <summary>
        /// Test the property 'OwnerId'
        /// </summary>
        [Fact]
        public void OwnerIdTest()
        {
            // TODO unit test for the property 'OwnerId'
        }

        /// <summary>
        /// Test the property 'SnapshotLimit'
        /// </summary>
        [Fact]
        public void SnapshotLimitTest()
        {
            // TODO unit test for the property 'SnapshotLimit'
        }

        /// <summary>
        /// Test the property 'FirewallPresets'
        /// </summary>
        [Fact]
        public void FirewallPresetsTest()
        {
            // TODO unit test for the property 'FirewallPresets'
        }

        /// <summary>
        /// Test the property 'ExtraStorage'
        /// </summary>
        [Fact]
        public void ExtraStorageTest()
        {
            // TODO unit test for the property 'ExtraStorage'
        }

        /// <summary>
        /// Test the property 'ExtraSize'
        /// </summary>
        [Fact]
        public void ExtraSizeTest()
        {
            // TODO unit test for the property 'ExtraSize'
        }

        /// <summary>
        /// Test the property 'ExtraMount'
        /// </summary>
        [Fact]
        public void ExtraMountTest()
        {
            // TODO unit test for the property 'ExtraMount'
        }

        /// <summary>
        /// Test the property 'Unprivileged'
        /// </summary>
        [Fact]
        public void UnprivilegedTest()
        {
            // TODO unit test for the property 'Unprivileged'
        }

        /// <summary>
        /// Test the property 'Nesting'
        /// </summary>
        [Fact]
        public void NestingTest()
        {
            // TODO unit test for the property 'Nesting'
        }

        /// <summary>
        /// Test the property 'Keyctl'
        /// </summary>
        [Fact]
        public void KeyctlTest()
        {
            // TODO unit test for the property 'Keyctl'
        }

        /// <summary>
        /// Test the property 'Fuse'
        /// </summary>
        [Fact]
        public void FuseTest()
        {
            // TODO unit test for the property 'Fuse'
        }

        /// <summary>
        /// Test the property 'Mount'
        /// </summary>
        [Fact]
        public void MountTest()
        {
            // TODO unit test for the property 'Mount'
        }

        /// <summary>
        /// Test the property 'Bios'
        /// </summary>
        [Fact]
        public void BiosTest()
        {
            // TODO unit test for the property 'Bios'
        }

        /// <summary>
        /// Test the property 'Machine'
        /// </summary>
        [Fact]
        public void MachineTest()
        {
            // TODO unit test for the property 'Machine'
        }

        /// <summary>
        /// Test the property 'Cpu'
        /// </summary>
        [Fact]
        public void CpuTest()
        {
            // TODO unit test for the property 'Cpu'
        }

        /// <summary>
        /// Test the property 'Vga'
        /// </summary>
        [Fact]
        public void VgaTest()
        {
            // TODO unit test for the property 'Vga'
        }
    }
}
