/*
 * NexoVirt REST API
 *
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NexoVirt.Sdk.Model;
using NexoVirt.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NexoVirt.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Plan
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlanTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Plan
        //private Plan instance;

        public PlanTests()
        {
            // TODO uncomment below to create an instance of Plan
            //instance = new Plan();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Plan
        /// </summary>
        [Fact]
        public void PlanInstanceTest()
        {
            // TODO uncomment below to test "IsType" Plan
            //Assert.IsType<Plan>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Cores'
        /// </summary>
        [Fact]
        public void CoresTest()
        {
            // TODO unit test for the property 'Cores'
        }

        /// <summary>
        /// Test the property 'MemoryMb'
        /// </summary>
        [Fact]
        public void MemoryMbTest()
        {
            // TODO unit test for the property 'MemoryMb'
        }

        /// <summary>
        /// Test the property 'DiskGb'
        /// </summary>
        [Fact]
        public void DiskGbTest()
        {
            // TODO unit test for the property 'DiskGb'
        }

        /// <summary>
        /// Test the property 'TrafficLimitGb'
        /// </summary>
        [Fact]
        public void TrafficLimitGbTest()
        {
            // TODO unit test for the property 'TrafficLimitGb'
        }

        /// <summary>
        /// Test the property 'RuntimeDays'
        /// </summary>
        [Fact]
        public void RuntimeDaysTest()
        {
            // TODO unit test for the property 'RuntimeDays'
        }

        /// <summary>
        /// Test the property 'GraceDays'
        /// </summary>
        [Fact]
        public void GraceDaysTest()
        {
            // TODO unit test for the property 'GraceDays'
        }

        /// <summary>
        /// Test the property 'SnapshotLimit'
        /// </summary>
        [Fact]
        public void SnapshotLimitTest()
        {
            // TODO unit test for the property 'SnapshotLimit'
        }
    }
}
