/*
 * NexoVirt REST API
 *
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = NexoVirt.Sdk.Client.FileParameter;
using OpenAPIDateConverter = NexoVirt.Sdk.Client.OpenAPIDateConverter;

namespace NexoVirt.Sdk.Model
{
    /// <summary>
    /// CreatePortForwardRequest
    /// </summary>
    [DataContract(Name = "createPortForward_request")]
    public partial class CreatePortForwardRequest : IValidatableObject
    {
        /// <summary>
        /// Defines Proto
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ProtoEnum
        {
            /// <summary>
            /// Enum Tcp for value: tcp
            /// </summary>
            [EnumMember(Value = "tcp")]
            Tcp = 1,

            /// <summary>
            /// Enum Udp for value: udp
            /// </summary>
            [EnumMember(Value = "udp")]
            Udp = 2
        }


        /// <summary>
        /// Gets or Sets Proto
        /// </summary>
        [DataMember(Name = "proto", IsRequired = true, EmitDefaultValue = true)]
        public ProtoEnum Proto { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatePortForwardRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreatePortForwardRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatePortForwardRequest" /> class.
        /// </summary>
        /// <param name="proto">proto (required).</param>
        /// <param name="publicPort">publicPort (required).</param>
        /// <param name="destIp">destIp (required).</param>
        /// <param name="destPort">destPort (required).</param>
        /// <param name="comment">comment.</param>
        public CreatePortForwardRequest(ProtoEnum proto = default, int publicPort = default, string destIp = default, int destPort = default, string comment = default)
        {
            this.Proto = proto;
            this.PublicPort = publicPort;
            // to ensure "destIp" is required (not null)
            if (destIp == null)
            {
                throw new ArgumentNullException("destIp is a required property for CreatePortForwardRequest and cannot be null");
            }
            this.DestIp = destIp;
            this.DestPort = destPort;
            this.Comment = comment;
        }

        /// <summary>
        /// Gets or Sets PublicPort
        /// </summary>
        [DataMember(Name = "public_port", IsRequired = true, EmitDefaultValue = true)]
        public int PublicPort { get; set; }

        /// <summary>
        /// Gets or Sets DestIp
        /// </summary>
        [DataMember(Name = "dest_ip", IsRequired = true, EmitDefaultValue = true)]
        public string DestIp { get; set; }

        /// <summary>
        /// Gets or Sets DestPort
        /// </summary>
        [DataMember(Name = "dest_port", IsRequired = true, EmitDefaultValue = true)]
        public int DestPort { get; set; }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>
        [DataMember(Name = "comment", EmitDefaultValue = false)]
        public string Comment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreatePortForwardRequest {\n");
            sb.Append("  Proto: ").Append(Proto).Append("\n");
            sb.Append("  PublicPort: ").Append(PublicPort).Append("\n");
            sb.Append("  DestIp: ").Append(DestIp).Append("\n");
            sb.Append("  DestPort: ").Append(DestPort).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
