/*
 * NexoVirt REST API
 *
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = NexoVirt.Sdk.Client.FileParameter;
using OpenAPIDateConverter = NexoVirt.Sdk.Client.OpenAPIDateConverter;

namespace NexoVirt.Sdk.Model
{
    /// <summary>
    /// CreateResellerGuestRequest
    /// </summary>
    [DataContract(Name = "createResellerGuest_request")]
    public partial class CreateResellerGuestRequest : IValidatableObject
    {
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Qemu for value: qemu
            /// </summary>
            [EnumMember(Value = "qemu")]
            Qemu = 1,

            /// <summary>
            /// Enum Lxc for value: lxc
            /// </summary>
            [EnumMember(Value = "lxc")]
            Lxc = 2
        }


        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Defines IpSource
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum IpSourceEnum
        {
            /// <summary>
            /// Enum Dhcp for value: dhcp
            /// </summary>
            [EnumMember(Value = "dhcp")]
            Dhcp = 1,

            /// <summary>
            /// Enum Zone for value: zone
            /// </summary>
            [EnumMember(Value = "zone")]
            Zone = 2
        }


        /// <summary>
        /// Gets or Sets IpSource
        /// </summary>
        [DataMember(Name = "ip_source", EmitDefaultValue = false)]
        public IpSourceEnum? IpSource { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateResellerGuestRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateResellerGuestRequest()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateResellerGuestRequest" /> class.
        /// </summary>
        /// <param name="ownerId">One of the calling reseller&#39;s own customer ids. (required).</param>
        /// <param name="hostId">hostId (required).</param>
        /// <param name="node">node (required).</param>
        /// <param name="type">type (required).</param>
        /// <param name="vmid">vmid (required).</param>
        /// <param name="name">name.</param>
        /// <param name="storage">storage (required).</param>
        /// <param name="planId">planId.</param>
        /// <param name="cores">cores.</param>
        /// <param name="memoryMb">memoryMb.</param>
        /// <param name="diskGb">diskGb.</param>
        /// <param name="bridge">bridge.</param>
        /// <param name="osTemplate">qemu &#x60;tpl:&lt;id&gt;&#x60; or lxc CT template volid..</param>
        /// <param name="ipSource">ipSource.</param>
        /// <param name="ipv4ZoneId">ipv4ZoneId.</param>
        /// <param name="ipv6ZoneId">ipv6ZoneId.</param>
        /// <param name="password">password.</param>
        public CreateResellerGuestRequest(int ownerId = default, int hostId = default, string node = default, TypeEnum type = default, int vmid = default, string name = default, string storage = default, int planId = default, int cores = default, int memoryMb = default, int diskGb = default, string bridge = default, string osTemplate = default, IpSourceEnum? ipSource = default, int ipv4ZoneId = default, int ipv6ZoneId = default, string password = default)
        {
            this.OwnerId = ownerId;
            this.HostId = hostId;
            // to ensure "node" is required (not null)
            if (node == null)
            {
                throw new ArgumentNullException("node is a required property for CreateResellerGuestRequest and cannot be null");
            }
            this.Node = node;
            this.Type = type;
            this.Vmid = vmid;
            // to ensure "storage" is required (not null)
            if (storage == null)
            {
                throw new ArgumentNullException("storage is a required property for CreateResellerGuestRequest and cannot be null");
            }
            this.Storage = storage;
            this.Name = name;
            this.PlanId = planId;
            this.Cores = cores;
            this.MemoryMb = memoryMb;
            this.DiskGb = diskGb;
            this.Bridge = bridge;
            this.OsTemplate = osTemplate;
            this.IpSource = ipSource;
            this.Ipv4ZoneId = ipv4ZoneId;
            this.Ipv6ZoneId = ipv6ZoneId;
            this.Password = password;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// One of the calling reseller&#39;s own customer ids.
        /// </summary>
        /// <value>One of the calling reseller&#39;s own customer ids.</value>
        [DataMember(Name = "owner_id", IsRequired = true, EmitDefaultValue = true)]
        public int OwnerId { get; set; }

        /// <summary>
        /// Gets or Sets HostId
        /// </summary>
        [DataMember(Name = "host_id", IsRequired = true, EmitDefaultValue = true)]
        public int HostId { get; set; }

        /// <summary>
        /// Gets or Sets Node
        /// </summary>
        [DataMember(Name = "node", IsRequired = true, EmitDefaultValue = true)]
        public string Node { get; set; }

        /// <summary>
        /// Gets or Sets Vmid
        /// </summary>
        [DataMember(Name = "vmid", IsRequired = true, EmitDefaultValue = true)]
        public int Vmid { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Storage
        /// </summary>
        [DataMember(Name = "storage", IsRequired = true, EmitDefaultValue = true)]
        public string Storage { get; set; }

        /// <summary>
        /// Gets or Sets PlanId
        /// </summary>
        [DataMember(Name = "plan_id", EmitDefaultValue = false)]
        public int PlanId { get; set; }

        /// <summary>
        /// Gets or Sets Cores
        /// </summary>
        [DataMember(Name = "cores", EmitDefaultValue = false)]
        public int Cores { get; set; }

        /// <summary>
        /// Gets or Sets MemoryMb
        /// </summary>
        [DataMember(Name = "memory_mb", EmitDefaultValue = false)]
        public int MemoryMb { get; set; }

        /// <summary>
        /// Gets or Sets DiskGb
        /// </summary>
        [DataMember(Name = "disk_gb", EmitDefaultValue = false)]
        public int DiskGb { get; set; }

        /// <summary>
        /// Gets or Sets Bridge
        /// </summary>
        [DataMember(Name = "bridge", EmitDefaultValue = false)]
        public string Bridge { get; set; }

        /// <summary>
        /// qemu &#x60;tpl:&lt;id&gt;&#x60; or lxc CT template volid.
        /// </summary>
        /// <value>qemu &#x60;tpl:&lt;id&gt;&#x60; or lxc CT template volid.</value>
        [DataMember(Name = "os_template", EmitDefaultValue = false)]
        public string OsTemplate { get; set; }

        /// <summary>
        /// Gets or Sets Ipv4ZoneId
        /// </summary>
        [DataMember(Name = "ipv4_zone_id", EmitDefaultValue = false)]
        public int Ipv4ZoneId { get; set; }

        /// <summary>
        /// Gets or Sets Ipv6ZoneId
        /// </summary>
        [DataMember(Name = "ipv6_zone_id", EmitDefaultValue = false)]
        public int Ipv6ZoneId { get; set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [DataMember(Name = "password", EmitDefaultValue = false)]
        public string Password { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateResellerGuestRequest {\n");
            sb.Append("  OwnerId: ").Append(OwnerId).Append("\n");
            sb.Append("  HostId: ").Append(HostId).Append("\n");
            sb.Append("  Node: ").Append(Node).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Vmid: ").Append(Vmid).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Storage: ").Append(Storage).Append("\n");
            sb.Append("  PlanId: ").Append(PlanId).Append("\n");
            sb.Append("  Cores: ").Append(Cores).Append("\n");
            sb.Append("  MemoryMb: ").Append(MemoryMb).Append("\n");
            sb.Append("  DiskGb: ").Append(DiskGb).Append("\n");
            sb.Append("  Bridge: ").Append(Bridge).Append("\n");
            sb.Append("  OsTemplate: ").Append(OsTemplate).Append("\n");
            sb.Append("  IpSource: ").Append(IpSource).Append("\n");
            sb.Append("  Ipv4ZoneId: ").Append(Ipv4ZoneId).Append("\n");
            sb.Append("  Ipv6ZoneId: ").Append(Ipv6ZoneId).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
