/*
 * NexoVirt REST API
 *
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = NexoVirt.Sdk.Client.FileParameter;
using OpenAPIDateConverter = NexoVirt.Sdk.Client.OpenAPIDateConverter;

namespace NexoVirt.Sdk.Model
{
    /// <summary>
    /// GuestListItem
    /// </summary>
    [DataContract(Name = "GuestListItem")]
    public partial class GuestListItem : IValidatableObject
    {
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Qemu for value: qemu
            /// </summary>
            [EnumMember(Value = "qemu")]
            Qemu = 1,

            /// <summary>
            /// Enum Lxc for value: lxc
            /// </summary>
            [EnumMember(Value = "lxc")]
            Lxc = 2
        }


        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GuestListItem" /> class.
        /// </summary>
        /// <param name="hostId">hostId.</param>
        /// <param name="host">host.</param>
        /// <param name="node">node.</param>
        /// <param name="vmid">vmid.</param>
        /// <param name="name">name.</param>
        /// <param name="type">type.</param>
        /// <param name="status">status.</param>
        /// <param name="os">The PVE ostype..</param>
        /// <param name="ip">ip.</param>
        /// <param name="cores">cores.</param>
        /// <param name="mem">Configured max memory in bytes..</param>
        /// <param name="storage">Configured max disk in bytes..</param>
        /// <param name="qemuAgent">Whether the QEMU guest agent is enabled. Null for LXC or when unknown..</param>
        /// <param name="tags">PVE tags, semicolon-joined (empty string when none). Searchable in the panel..</param>
        public GuestListItem(int hostId = default, string host = default, string node = default, int vmid = default, string name = default, TypeEnum? type = default, string status = default, string os = default, string ip = default, int cores = default, int mem = default, int storage = default, bool? qemuAgent = default, string tags = default)
        {
            this.HostId = hostId;
            this.Host = host;
            this.Node = node;
            this.Vmid = vmid;
            this.Name = name;
            this.Type = type;
            this.Status = status;
            this.Os = os;
            this.Ip = ip;
            this.Cores = cores;
            this.Mem = mem;
            this.Storage = storage;
            this.QemuAgent = qemuAgent;
            this.Tags = tags;
        }

        /// <summary>
        /// Gets or Sets HostId
        /// </summary>
        /*
        <example>1</example>
        */
        [DataMember(Name = "host_id", EmitDefaultValue = false)]
        public int HostId { get; set; }

        /// <summary>
        /// Gets or Sets Host
        /// </summary>
        /*
        <example>Test</example>
        */
        [DataMember(Name = "host", EmitDefaultValue = false)]
        public string Host { get; set; }

        /// <summary>
        /// Gets or Sets Node
        /// </summary>
        /*
        <example>pve1</example>
        */
        [DataMember(Name = "node", EmitDefaultValue = false)]
        public string Node { get; set; }

        /// <summary>
        /// Gets or Sets Vmid
        /// </summary>
        /*
        <example>105</example>
        */
        [DataMember(Name = "vmid", EmitDefaultValue = false)]
        public int Vmid { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /*
        <example>web-01</example>
        */
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        /*
        <example>running</example>
        */
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// The PVE ostype.
        /// </summary>
        /// <value>The PVE ostype.</value>
        /*
        <example>l26</example>
        */
        [DataMember(Name = "os", EmitDefaultValue = false)]
        public string Os { get; set; }

        /// <summary>
        /// Gets or Sets Ip
        /// </summary>
        /*
        <example>10.10.0.5</example>
        */
        [DataMember(Name = "ip", EmitDefaultValue = false)]
        public string Ip { get; set; }

        /// <summary>
        /// Gets or Sets Cores
        /// </summary>
        /*
        <example>2</example>
        */
        [DataMember(Name = "cores", EmitDefaultValue = false)]
        public int Cores { get; set; }

        /// <summary>
        /// Configured max memory in bytes.
        /// </summary>
        /// <value>Configured max memory in bytes.</value>
        [DataMember(Name = "mem", EmitDefaultValue = false)]
        public int Mem { get; set; }

        /// <summary>
        /// Configured max disk in bytes.
        /// </summary>
        /// <value>Configured max disk in bytes.</value>
        [DataMember(Name = "storage", EmitDefaultValue = false)]
        public int Storage { get; set; }

        /// <summary>
        /// Whether the QEMU guest agent is enabled. Null for LXC or when unknown.
        /// </summary>
        /// <value>Whether the QEMU guest agent is enabled. Null for LXC or when unknown.</value>
        [DataMember(Name = "qemu_agent", EmitDefaultValue = true)]
        public bool? QemuAgent { get; set; }

        /// <summary>
        /// PVE tags, semicolon-joined (empty string when none). Searchable in the panel.
        /// </summary>
        /// <value>PVE tags, semicolon-joined (empty string when none). Searchable in the panel.</value>
        /*
        <example>prod;web</example>
        */
        [DataMember(Name = "tags", EmitDefaultValue = false)]
        public string Tags { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GuestListItem {\n");
            sb.Append("  HostId: ").Append(HostId).Append("\n");
            sb.Append("  Host: ").Append(Host).Append("\n");
            sb.Append("  Node: ").Append(Node).Append("\n");
            sb.Append("  Vmid: ").Append(Vmid).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Os: ").Append(Os).Append("\n");
            sb.Append("  Ip: ").Append(Ip).Append("\n");
            sb.Append("  Cores: ").Append(Cores).Append("\n");
            sb.Append("  Mem: ").Append(Mem).Append("\n");
            sb.Append("  Storage: ").Append(Storage).Append("\n");
            sb.Append("  QemuAgent: ").Append(QemuAgent).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
