/*
 * NexoVirt REST API
 *
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = NexoVirt.Sdk.Client.FileParameter;
using OpenAPIDateConverter = NexoVirt.Sdk.Client.OpenAPIDateConverter;

namespace NexoVirt.Sdk.Model
{
    /// <summary>
    /// NetworkInterface
    /// </summary>
    [DataContract(Name = "NetworkInterface")]
    public partial class NetworkInterface : IValidatableObject
    {
        /// <summary>
        /// Defines Role
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RoleEnum
        {
            /// <summary>
            /// Enum WAN for value: WAN
            /// </summary>
            [EnumMember(Value = "WAN")]
            WAN = 1,

            /// <summary>
            /// Enum Private for value: Private
            /// </summary>
            [EnumMember(Value = "Private")]
            Private = 2,

            /// <summary>
            /// Enum Internal for value: Internal
            /// </summary>
            [EnumMember(Value = "Internal")]
            Internal = 3,

            /// <summary>
            /// Enum Other for value: Other
            /// </summary>
            [EnumMember(Value = "Other")]
            Other = 4
        }


        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [DataMember(Name = "role", EmitDefaultValue = false)]
        public RoleEnum? Role { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkInterface" /> class.
        /// </summary>
        /// <param name="iface">iface.</param>
        /// <param name="node">node.</param>
        /// <param name="type">type.</param>
        /// <param name="role">role.</param>
        /// <param name="cidr">cidr.</param>
        /// <param name="gateway">gateway.</param>
        /// <param name="ports">ports.</param>
        /// <param name="active">active.</param>
        public NetworkInterface(string iface = default, string node = default, string type = default, RoleEnum? role = default, string cidr = default, string gateway = default, string ports = default, bool active = default)
        {
            this.Iface = iface;
            this.Node = node;
            this.Type = type;
            this.Role = role;
            this.Cidr = cidr;
            this.Gateway = gateway;
            this.Ports = ports;
            this.Active = active;
        }

        /// <summary>
        /// Gets or Sets Iface
        /// </summary>
        /*
        <example>vmbr0</example>
        */
        [DataMember(Name = "iface", EmitDefaultValue = false)]
        public string Iface { get; set; }

        /// <summary>
        /// Gets or Sets Node
        /// </summary>
        /*
        <example>pve1</example>
        */
        [DataMember(Name = "node", EmitDefaultValue = false)]
        public string Node { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        /*
        <example>bridge</example>
        */
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Cidr
        /// </summary>
        /*
        <example>203.0.113.0/24</example>
        */
        [DataMember(Name = "cidr", EmitDefaultValue = false)]
        public string Cidr { get; set; }

        /// <summary>
        /// Gets or Sets Gateway
        /// </summary>
        /*
        <example>203.0.113.1</example>
        */
        [DataMember(Name = "gateway", EmitDefaultValue = false)]
        public string Gateway { get; set; }

        /// <summary>
        /// Gets or Sets Ports
        /// </summary>
        /*
        <example>eno1</example>
        */
        [DataMember(Name = "ports", EmitDefaultValue = false)]
        public string Ports { get; set; }

        /// <summary>
        /// Gets or Sets Active
        /// </summary>
        [DataMember(Name = "active", EmitDefaultValue = true)]
        public bool Active { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NetworkInterface {\n");
            sb.Append("  Iface: ").Append(Iface).Append("\n");
            sb.Append("  Node: ").Append(Node).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  Cidr: ").Append(Cidr).Append("\n");
            sb.Append("  Gateway: ").Append(Gateway).Append("\n");
            sb.Append("  Ports: ").Append(Ports).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
