/*
 * NexoVirt REST API
 *
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = NexoVirt.Sdk.Client.FileParameter;
using OpenAPIDateConverter = NexoVirt.Sdk.Client.OpenAPIDateConverter;

namespace NexoVirt.Sdk.Model
{
    /// <summary>
    /// Plan
    /// </summary>
    [DataContract(Name = "Plan")]
    public partial class Plan : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Plan" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="description">description.</param>
        /// <param name="cores">cores.</param>
        /// <param name="memoryMb">memoryMb.</param>
        /// <param name="diskGb">diskGb.</param>
        /// <param name="trafficLimitGb">Monthly traffic limit. 0 means unlimited..</param>
        /// <param name="runtimeDays">Expiry in days. 0 means unlimited..</param>
        /// <param name="graceDays">Grace period before auto-delete after expiry..</param>
        /// <param name="snapshotLimit">snapshotLimit.</param>
        public Plan(int id = default, string name = default, string description = default, int cores = default, int memoryMb = default, int diskGb = default, int trafficLimitGb = default, int runtimeDays = default, int graceDays = default, int snapshotLimit = default)
        {
            this.Id = id;
            this.Name = name;
            this.Description = description;
            this.Cores = cores;
            this.MemoryMb = memoryMb;
            this.DiskGb = diskGb;
            this.TrafficLimitGb = trafficLimitGb;
            this.RuntimeDays = runtimeDays;
            this.GraceDays = graceDays;
            this.SnapshotLimit = snapshotLimit;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /*
        <example>2</example>
        */
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /*
        <example>Standard</example>
        */
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Cores
        /// </summary>
        /*
        <example>2</example>
        */
        [DataMember(Name = "cores", EmitDefaultValue = false)]
        public int Cores { get; set; }

        /// <summary>
        /// Gets or Sets MemoryMb
        /// </summary>
        /*
        <example>2048</example>
        */
        [DataMember(Name = "memory_mb", EmitDefaultValue = false)]
        public int MemoryMb { get; set; }

        /// <summary>
        /// Gets or Sets DiskGb
        /// </summary>
        /*
        <example>20</example>
        */
        [DataMember(Name = "disk_gb", EmitDefaultValue = false)]
        public int DiskGb { get; set; }

        /// <summary>
        /// Monthly traffic limit. 0 means unlimited.
        /// </summary>
        /// <value>Monthly traffic limit. 0 means unlimited.</value>
        [DataMember(Name = "traffic_limit_gb", EmitDefaultValue = false)]
        public int TrafficLimitGb { get; set; }

        /// <summary>
        /// Expiry in days. 0 means unlimited.
        /// </summary>
        /// <value>Expiry in days. 0 means unlimited.</value>
        [DataMember(Name = "runtime_days", EmitDefaultValue = false)]
        public int RuntimeDays { get; set; }

        /// <summary>
        /// Grace period before auto-delete after expiry.
        /// </summary>
        /// <value>Grace period before auto-delete after expiry.</value>
        [DataMember(Name = "grace_days", EmitDefaultValue = false)]
        public int GraceDays { get; set; }

        /// <summary>
        /// Gets or Sets SnapshotLimit
        /// </summary>
        [DataMember(Name = "snapshot_limit", EmitDefaultValue = false)]
        public int SnapshotLimit { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Plan {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Cores: ").Append(Cores).Append("\n");
            sb.Append("  MemoryMb: ").Append(MemoryMb).Append("\n");
            sb.Append("  DiskGb: ").Append(DiskGb).Append("\n");
            sb.Append("  TrafficLimitGb: ").Append(TrafficLimitGb).Append("\n");
            sb.Append("  RuntimeDays: ").Append(RuntimeDays).Append("\n");
            sb.Append("  GraceDays: ").Append(GraceDays).Append("\n");
            sb.Append("  SnapshotLimit: ").Append(SnapshotLimit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
