/*
 * NexoVirt REST API
 *
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = NexoVirt.Sdk.Client.FileParameter;
using OpenAPIDateConverter = NexoVirt.Sdk.Client.OpenAPIDateConverter;

namespace NexoVirt.Sdk.Model
{
    /// <summary>
    /// PowerGuestRequest
    /// </summary>
    [DataContract(Name = "powerGuest_request")]
    public partial class PowerGuestRequest : IValidatableObject
    {
        /// <summary>
        /// Defines Action
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ActionEnum
        {
            /// <summary>
            /// Enum Start for value: start
            /// </summary>
            [EnumMember(Value = "start")]
            Start = 1,

            /// <summary>
            /// Enum Stop for value: stop
            /// </summary>
            [EnumMember(Value = "stop")]
            Stop = 2,

            /// <summary>
            /// Enum Shutdown for value: shutdown
            /// </summary>
            [EnumMember(Value = "shutdown")]
            Shutdown = 3,

            /// <summary>
            /// Enum Reboot for value: reboot
            /// </summary>
            [EnumMember(Value = "reboot")]
            Reboot = 4,

            /// <summary>
            /// Enum Suspend for value: suspend
            /// </summary>
            [EnumMember(Value = "suspend")]
            Suspend = 5,

            /// <summary>
            /// Enum Resume for value: resume
            /// </summary>
            [EnumMember(Value = "resume")]
            Resume = 6
        }


        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [DataMember(Name = "action", IsRequired = true, EmitDefaultValue = true)]
        public ActionEnum Action { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PowerGuestRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PowerGuestRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PowerGuestRequest" /> class.
        /// </summary>
        /// <param name="node">The PVE node the guest currently lives on. (required).</param>
        /// <param name="action">action (required).</param>
        public PowerGuestRequest(string node = default, ActionEnum action = default)
        {
            // to ensure "node" is required (not null)
            if (node == null)
            {
                throw new ArgumentNullException("node is a required property for PowerGuestRequest and cannot be null");
            }
            this.Node = node;
            this.Action = action;
        }

        /// <summary>
        /// The PVE node the guest currently lives on.
        /// </summary>
        /// <value>The PVE node the guest currently lives on.</value>
        [DataMember(Name = "node", IsRequired = true, EmitDefaultValue = true)]
        public string Node { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PowerGuestRequest {\n");
            sb.Append("  Node: ").Append(Node).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
