/*
 * NexoVirt REST API
 *
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = NexoVirt.Sdk.Client.FileParameter;
using OpenAPIDateConverter = NexoVirt.Sdk.Client.OpenAPIDateConverter;

namespace NexoVirt.Sdk.Model
{
    /// <summary>
    /// ResellerPlan
    /// </summary>
    [DataContract(Name = "ResellerPlan")]
    public partial class ResellerPlan : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResellerPlan" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ResellerPlan() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ResellerPlan" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="description">description.</param>
        /// <param name="maxCustomers">0 &#x3D; unlimited..</param>
        /// <param name="maxGuests">0 &#x3D; unlimited..</param>
        /// <param name="maxCores">0 &#x3D; unlimited..</param>
        /// <param name="maxMemoryMb">0 &#x3D; unlimited..</param>
        /// <param name="maxDiskGb">0 &#x3D; unlimited..</param>
        /// <param name="isActive">isActive.</param>
        /// <param name="id">id.</param>
        public ResellerPlan(string name = default, string description = default, int maxCustomers = default, int maxGuests = default, int maxCores = default, int maxMemoryMb = default, int maxDiskGb = default, bool isActive = default, int id = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ResellerPlan and cannot be null");
            }
            this.Name = name;
            this.Description = description;
            this.MaxCustomers = maxCustomers;
            this.MaxGuests = maxGuests;
            this.MaxCores = maxCores;
            this.MaxMemoryMb = maxMemoryMb;
            this.MaxDiskGb = maxDiskGb;
            this.IsActive = isActive;
            this.Id = id;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// 0 &#x3D; unlimited.
        /// </summary>
        /// <value>0 &#x3D; unlimited.</value>
        [DataMember(Name = "max_customers", EmitDefaultValue = false)]
        public int MaxCustomers { get; set; }

        /// <summary>
        /// 0 &#x3D; unlimited.
        /// </summary>
        /// <value>0 &#x3D; unlimited.</value>
        [DataMember(Name = "max_guests", EmitDefaultValue = false)]
        public int MaxGuests { get; set; }

        /// <summary>
        /// 0 &#x3D; unlimited.
        /// </summary>
        /// <value>0 &#x3D; unlimited.</value>
        [DataMember(Name = "max_cores", EmitDefaultValue = false)]
        public int MaxCores { get; set; }

        /// <summary>
        /// 0 &#x3D; unlimited.
        /// </summary>
        /// <value>0 &#x3D; unlimited.</value>
        [DataMember(Name = "max_memory_mb", EmitDefaultValue = false)]
        public int MaxMemoryMb { get; set; }

        /// <summary>
        /// 0 &#x3D; unlimited.
        /// </summary>
        /// <value>0 &#x3D; unlimited.</value>
        [DataMember(Name = "max_disk_gb", EmitDefaultValue = false)]
        public int MaxDiskGb { get; set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        [DataMember(Name = "is_active", EmitDefaultValue = true)]
        public bool IsActive { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /*
        <example>2</example>
        */
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResellerPlan {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  MaxCustomers: ").Append(MaxCustomers).Append("\n");
            sb.Append("  MaxGuests: ").Append(MaxGuests).Append("\n");
            sb.Append("  MaxCores: ").Append(MaxCores).Append("\n");
            sb.Append("  MaxMemoryMb: ").Append(MaxMemoryMb).Append("\n");
            sb.Append("  MaxDiskGb: ").Append(MaxDiskGb).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
