/*
 * NexoVirt REST API
 *
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = NexoVirt.Sdk.Client.FileParameter;
using OpenAPIDateConverter = NexoVirt.Sdk.Client.OpenAPIDateConverter;

namespace NexoVirt.Sdk.Model
{
    /// <summary>
    /// SetGuestIpconfigRequest
    /// </summary>
    [DataContract(Name = "setGuestIpconfig_request")]
    public partial class SetGuestIpconfigRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetGuestIpconfigRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SetGuestIpconfigRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SetGuestIpconfigRequest" /> class.
        /// </summary>
        /// <param name="node">The PVE node the guest currently lives on. (required).</param>
        /// <param name="ipconfig">For example \&quot;ip&#x3D;dhcp\&quot; or \&quot;ip&#x3D;1.2.3.4/24,gw&#x3D;1.2.3.1\&quot;. (required).</param>
        /// <param name="bridge">Defaults to vmbr0..</param>
        public SetGuestIpconfigRequest(string node = default, string ipconfig = default, string bridge = default)
        {
            // to ensure "node" is required (not null)
            if (node == null)
            {
                throw new ArgumentNullException("node is a required property for SetGuestIpconfigRequest and cannot be null");
            }
            this.Node = node;
            // to ensure "ipconfig" is required (not null)
            if (ipconfig == null)
            {
                throw new ArgumentNullException("ipconfig is a required property for SetGuestIpconfigRequest and cannot be null");
            }
            this.Ipconfig = ipconfig;
            this.Bridge = bridge;
        }

        /// <summary>
        /// The PVE node the guest currently lives on.
        /// </summary>
        /// <value>The PVE node the guest currently lives on.</value>
        [DataMember(Name = "node", IsRequired = true, EmitDefaultValue = true)]
        public string Node { get; set; }

        /// <summary>
        /// For example \&quot;ip&#x3D;dhcp\&quot; or \&quot;ip&#x3D;1.2.3.4/24,gw&#x3D;1.2.3.1\&quot;.
        /// </summary>
        /// <value>For example \&quot;ip&#x3D;dhcp\&quot; or \&quot;ip&#x3D;1.2.3.4/24,gw&#x3D;1.2.3.1\&quot;.</value>
        [DataMember(Name = "ipconfig", IsRequired = true, EmitDefaultValue = true)]
        public string Ipconfig { get; set; }

        /// <summary>
        /// Defaults to vmbr0.
        /// </summary>
        /// <value>Defaults to vmbr0.</value>
        [DataMember(Name = "bridge", EmitDefaultValue = false)]
        public string Bridge { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SetGuestIpconfigRequest {\n");
            sb.Append("  Node: ").Append(Node).Append("\n");
            sb.Append("  Ipconfig: ").Append(Ipconfig).Append("\n");
            sb.Append("  Bridge: ").Append(Bridge).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
