/*
 * NexoVirt REST API
 *
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using NexoVirt.Sdk.Client;
using NexoVirt.Sdk.Api;
// uncomment below to import models
//using NexoVirt.Sdk.Model;

namespace NexoVirt.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing NetworkingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class NetworkingApiTests : IDisposable
    {
        private NetworkingApi instance;

        public NetworkingApiTests()
        {
            instance = new NetworkingApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NetworkingApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' NetworkingApi
            //Assert.IsType<NetworkingApi>(instance);
        }

        /// <summary>
        /// Test ApplyNat
        /// </summary>
        [Fact]
        public void ApplyNatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int hostId = null;
            //var response = instance.ApplyNat(hostId);
            //Assert.IsType<Envelope>(response);
        }

        /// <summary>
        /// Test CreatePortForward
        /// </summary>
        [Fact]
        public void CreatePortForwardTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int hostId = null;
            //CreatePortForwardRequest createPortForwardRequest = null;
            //var response = instance.CreatePortForward(hostId, createPortForwardRequest);
            //Assert.IsType<Envelope>(response);
        }

        /// <summary>
        /// Test DeletePortForward
        /// </summary>
        [Fact]
        public void DeletePortForwardTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int hostId = null;
            //int pfId = null;
            //var response = instance.DeletePortForward(hostId, pfId);
            //Assert.IsType<Envelope>(response);
        }

        /// <summary>
        /// Test GetNat
        /// </summary>
        [Fact]
        public void GetNatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int hostId = null;
            //var response = instance.GetNat(hostId);
            //Assert.IsType<Envelope>(response);
        }

        /// <summary>
        /// Test SetNatSettings
        /// </summary>
        [Fact]
        public void SetNatSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int hostId = null;
            //SetNatSettingsRequest setNatSettingsRequest = null;
            //var response = instance.SetNatSettings(hostId, setNatSettingsRequest);
            //Assert.IsType<Envelope>(response);
        }
    }
}
