/*
 * NexoVirt REST API
 *
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using NexoVirt.Sdk.Client;
using NexoVirt.Sdk.Api;
// uncomment below to import models
//using NexoVirt.Sdk.Model;

namespace NexoVirt.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing ResellerCustomersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ResellerCustomersApiTests : IDisposable
    {
        private ResellerCustomersApi instance;

        public ResellerCustomersApiTests()
        {
            instance = new ResellerCustomersApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResellerCustomersApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ResellerCustomersApi
            //Assert.IsType<ResellerCustomersApi>(instance);
        }

        /// <summary>
        /// Test CreateResellerCustomer
        /// </summary>
        [Fact]
        public void CreateResellerCustomerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateResellerRequest createResellerRequest = null;
            //var response = instance.CreateResellerCustomer(createResellerRequest);
            //Assert.IsType<CreateReseller200Response>(response);
        }

        /// <summary>
        /// Test DeleteResellerCustomer
        /// </summary>
        [Fact]
        public void DeleteResellerCustomerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int customerId = null;
            //var response = instance.DeleteResellerCustomer(customerId);
            //Assert.IsType<Envelope>(response);
        }

        /// <summary>
        /// Test GetResellerCustomer
        /// </summary>
        [Fact]
        public void GetResellerCustomerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int customerId = null;
            //var response = instance.GetResellerCustomer(customerId);
            //Assert.IsType<Envelope>(response);
        }

        /// <summary>
        /// Test ListResellerCustomers
        /// </summary>
        [Fact]
        public void ListResellerCustomersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? perPage = null;
            //var response = instance.ListResellerCustomers(page, perPage);
            //Assert.IsType<ListResellerCustomers200Response>(response);
        }

        /// <summary>
        /// Test ResellerPing
        /// </summary>
        [Fact]
        public void ResellerPingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ResellerPing();
            //Assert.IsType<Envelope>(response);
        }

        /// <summary>
        /// Test ResetResellerCustomerPassword
        /// </summary>
        [Fact]
        public void ResetResellerCustomerPasswordTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int customerId = null;
            //var response = instance.ResetResellerCustomerPassword(customerId);
            //Assert.IsType<Envelope>(response);
        }

        /// <summary>
        /// Test UpdateResellerCustomer
        /// </summary>
        [Fact]
        public void UpdateResellerCustomerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int customerId = null;
            //UpdateResellerRequest updateResellerRequest = null;
            //var response = instance.UpdateResellerCustomer(customerId, updateResellerRequest);
            //Assert.IsType<Envelope>(response);
        }

        /// <summary>
        /// Test UpdateResellerCustomerPost
        /// </summary>
        [Fact]
        public void UpdateResellerCustomerPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int customerId = null;
            //UpdateResellerRequest updateResellerRequest = null;
            //var response = instance.UpdateResellerCustomerPost(customerId, updateResellerRequest);
            //Assert.IsType<Envelope>(response);
        }
    }
}
